name: Build

on:
  push:
    branches: ["master"]
    paths-ignore:
      - 'README.md'
  pull_request:


jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-14 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.12.0

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}

      - name: Remove Android's cmake
        shell: bash
        run: rm -rf $ANDROID_HOME/cmake

      - name: Build with Gradle
        run: |
          ccache -o cache_dir=${{ github.workspace }}/.ccache
          ccache -o hash_dir=false
          ccache -o compiler_check='%compiler% -dumpmachine; %compiler% -dumpversion'
          ccache -p
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          ./gradlew :lsplant:publishToMavenLocal :lsplant:prefabDebugPackage
          ./gradlew --stop
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.maven_pgp_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_pgp_signingPassword }}

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-library
          path: ~/.m2
